### ISSUE TITLE
Feature Request: Enforce `@default([])` for Arrays

### ISSUE THREAD

**Issue by PavlMais** [loop-payments/prisma-lint#275]
## Reason
Let's assume we have this scheme 
```prisma
model Post {
  tags String[]
}
```
and add a few posts
```ts
await prisma.posts.createMany({
  data: [
    { tags: ['nature'] },    
    { tags: undefined },
  ].
})
```
this is how they looks in Postgres database
| tags  | 
| ------------- |
| {nature}  | 
| NULL  | 

now, attempting to filter posts without any tags
```ts
const posts = await prisma.posts.findMany({
  where: {
    tags: { isEmpty: true }  
  },
});
```
this will not return any posts, so it can be very confusing sometimes

## Rule Example
```prisma
// good
model Post {
  tags String[] @default([])
}

// bad
model Post {
  tags String[]
}
```

**Comment by maxh** [comment]
Make sense. Thanks for suggesting. It will probably be most similar in implementation to this one:
https://github.com/loop-payments/prisma-lint/blob/main/src/rules/field-name-mapping-snake-case.ts

You're welcome to take a stab implementing, or I can take a look in the new year. More info if you'd like to try:
https://github.com/loop-payments/prisma-lint/blob/main/DEVELOPMENT.md

**Comment by maxh** [comment]
@PavlMais please take a look: https://github.com/loop-payments/prisma-lint/pull/280
