### ISSUE TITLE
Can we use it as an eslint plugin

### ISSUE THREAD

**Issue by larryro** [loop-payments/prisma-lint#297]
Hi, thank you for your awsome work.  

we are using monorepo and using eslint to lint our projects. Separately Introducing the prisma-lint tool in the process is a bit heavy, can it be configured as a plugin under the overrides field in the .eslintrc.json file?

**Comment by maxh** [comment]
Eslint is for JavaScript / TypeScript source code. prisma-lint is for Prisma schema source code. Though the pattern of behavior is similar, the implementations are different. prisma-lint is based on a different AST and set of tooling unrelated to JavaScript.

What are you finding difficult about integrating prisma-lint? It should take <30 minutes to set up for a new repo.
