### ISSUE TITLE
Support exceptions for the `Expected singular model name. model-name-grammatical-number` error

### ISSUE THREAD

**Issue by kibertoad** [loop-payments/prisma-lint#354]
Similarly to how `model-name-mapping-snake-case` has a list of compound words, `model-name-grammatical-number` should support a list of exceptions too. E. g. `settings` or `scissors` are _singular_, it makes no sense to create a table `setting` or `scissor`.

**Comment by maxh** [comment]
Makes sense. Internally we simply disable the rule with in-line comments on such models, but adding this to the config is a good idea.

**Comment by maxh** [comment]
Example:

```prisma
model ArtifactMetadata {
  /// prisma-lint-ignore-model model-name-grammatical-number
}
```

**Comment by kibertoad** [comment]
Yeah, that's what we did as a short-term solution, but having proper config would be nice :D

**Comment by maxh** [comment]
Does this support your use case? https://github.com/loop-payments/prisma-lint/pull/356

**Comment by kibertoad** [comment]
This is perfect, thanks!
