### ISSUE TITLE
Handle case where name is omitted for `@map` and `@@map`

### ISSUE THREAD

**Issue by mcmxcdev** [loop-payments/prisma-lint#59]
We run into a lot of lint warnings for `model-name-mapping-snake-case` and `field-name-mapping-snake-case` because we use e.g. `@@map("allowance_model")` rather than `@@map(name: "allowance_model")`. The first way runs into lint warnings while the latter is fine.

According to https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#map-1, "the name of the name argument on the `@@map` attribute can be omitted".

Looking at the whole Prisma schema reference, there are a lot of attributes which can have omitted arguments, so multiple ways of writing it need to be considered.

**Comment by maxh** [comment]
Thanks! This should fix: https://github.com/loop-payments/prisma-lint/pull/60

**Comment by mcmxcdev** [comment]
Cool, that was quick!

You should search the whole prisma schema reference for "can be omitted" to make sure that you handle all relevant cases according to the existing lint rules.

**Comment by maxh** [comment]
I believe the only other existing rule that would be affected is the `required-field-index` rule. I've added test cases to ensure we support the case with and without key: https://github.com/loop-payments/prisma-lint/pull/61. Seems that one is already good.

Let me know your thoughts on `0.0.18` once https://github.com/loop-payments/prisma-lint/pull/62 merges and publishes. Thanks again!

**Comment by mcmxcdev** [comment]
Works great now ;) 

Already discovered some annoying inconsistencies in our schema.
